FROM ubuntu:latest

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    build-essential \
    gcc \
    libc6-dev \
    make \
    && rm -rf /var/lib/apt/lists/*

COPY . /app

WORKDIR /app

RUN make

CMD ["./FdF"]
